### ISSUE TITLE
Class IoTextCodec in decode method have bug or bug exists in implementation

### ISSUE THREAD

**Issue by bieli** [bieli/IoText-data-protocol#1]
Unit test skipped - to fixing - is [here](https://github.com/bieli/IoText-data-protocol/blob/ab037f3e16da3373a5320af2cfc1d8b3bb684945/tests/codecs/test_iot_ext_codec.py#L17)

**Comment by bieli** [comment]
Solution to review https://github.com/bieli/IoText-data-protocol/pull/5
Thx @ksyuzi

**Comment by przemek1236** [comment]
So it looks like there are 2 dataclasses defined with exactly the same name `Item`, one resides in types/item.py and second one is inside of `types/item_type.py` and both are exactly the same. Implementation of the library in src uses former, where tests uses the one from the latter. This causes the error at the very beginning because instances are of a different classes.
@ksyuzi

**Comment by ksyuzi** [comment]
@przemek1236 thank you, but the explanation wasn't necessary, I figured it out and committed this fix. 
@bieli both tests now pass, so no need for the TODO. please, take a look.

**Comment by bieli** [comment]
Great contribution ;-)

I merged solution today and propose next bug fixes here #12 (+ code coverage)
